server:
  port: 9000

spring:
  datasource:
    url: jdbc:h2:mem:sentrycdb
    username: admin
    password: admin
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect